name: 'EUserv Auto Extend'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 2,3,4 * *'
  watch:
    types: started

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade requests
          python -m pip install --upgrade beautifulsoup4

      - name: 'Auto_renew'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python main.py
      
      - name: 'Random upload to avoid Github Workflow suspend'
        run: echo `date +"%Y-%m-%d %H:%M:%S"` >> timenow.txt
     
      - name: Commit Files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -am 'run'
          echo ::set-output name=status::success
           
      - name: GitHub Push
        if: steps.commit.output.status != 'success'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
